# .goreleaser.yaml
project_name: devex

builds:
  - id: contributions
    main: ./cmd/contributions
    binary: devex-contributions
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
  - id: sre
    main: ./cmd/sre
    binary: devex-sre
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
  - id: workplan
    main: ./cmd/workplan
    binary: devex-workplan
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - id: contributions-archive
    # This links this archive block ONLY to the contributions build
    builds:
      - contributions
    name_template: "pi-contributions_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

  - id: sre-archive
    builds:
      - sre
    name_template: "pi-sre_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

  - id: workplan-archive
    builds:
      - workplan
    name_template: "pi-workplan_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz