[tools]
go = "1.26.0"
golangci-lint = "2.10.1"
awscli = "2.34.2"

[env]
MISE_DISABLE_BACKENDS = "aqua,ubi"

[settings]
experimental = true

# Commands

[tasks.aiprompt]
run = "go run cmd/aiprompt/main.go"

[tasks.components]
run = "go run cmd/components/main.go"

[tasks.contributions]
run = "go run cmd/contributions/main.go"

[tasks.keygen]
run = "go run cmd/keygen/main.go"

[tasks.pgaccess]
run = "go run cmd/pgaccess/main.go"

[tasks.workplan]
run = "go run cmd/workplan/main.go"

# Testing

[tasks.test]
run = "go test ./... -v"

# Linting

[tasks.lint]
run = "golangci-lint run --fix"

[tasks.format]
run = "go fmt ./..."

# Release

[tasks.release]
run = "go run cmd/release/main.go"
