[tools]
go = "1.26.1"
golangci-lint = "2.11.2"
awscli = "2.34.4"
node = "25.8.0"
prettier = "3.8.1"

[env]
MISE_DISABLE_BACKENDS = "aqua,ubi"

[settings]
experimental = true

# Commands

[tasks.analyze]
run = "mise sre analyze"

[tasks.components]
run = "go run cmd/components/main.go"

[tasks.contributions]
run = "go run cmd/contributions/main.go"

[tasks.keygen]
run = "mise sre keygen"

[tasks.pgaccess]
run = "mise sre postgres access"

[tasks.release]
run = "mise sre release"

[tasks.sre]
run = "go run cmd/sre/main.go"

[tasks.workplan]
run = "go run cmd/workplan/main.go"

# Testing

[tasks.test]
run = "go test ./... -v"

# Linting

[tasks.lint]
depends = ["lint-*"]

[tasks.lint-go]
run = "golangci-lint run --fix"

[tasks.lint-prettier]
depends = ["format-prettier-sync"]
run = "prettier --check ."

[tasks.format]
depends = ["format-*"]

[tasks.format-prettier-sync]
run = "sh ./scripts/sync-prettier-config.sh"

[tasks.format-prettier]
depends = ["format-prettier-sync"]
run = "prettier --write ."

[tasks.format-go]
run = "go fmt ./..."
