package config

type LocalizeConfiguration struct {
	// LocalesDir is the root directory containing locale subdirectories (e.g., "en-US", "es-US")
	LocalesDir string `yaml:"localesDir"`

	// RubricPath is an optional path to a text/markdown file containing translation rules,
	// legal terms, and pre-defined translation strings to guide the LLM.
	RubricPath string `yaml:"rubricPath"`

	// SourceFilename is the name of the file generated by gotext (default "out.gotext.json")
	SourceFilename string `yaml:"sourceFilename"`

	// TargetFilename is the name of the file containing translated strings (default "messages.gotext.json")
	TargetFilename string `yaml:"targetFilename"`
}
